#!/bin/bash
yum update -y
yum install docker git -y
git clone https://github.com/gmendonca/devops-apps.git
cd devops-apps/python_app/
sudo service docker start
sudo docker build -t python-app .
sudo docker run -p 80:5000 python-app
